version: '3'

services: 
  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=1234
    ports: 
      - "5432:5432"
    networks: 
      - node-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
networks: 
  node-network:
    driver: bridge    