version: '3'

services: 
  # backend:
  #   build: 
  #     context: node
  #   container_name: backend
  #   working_dir: /usr/src/app
  #   networks: 
  #     - node-network
  #   volumes: 
  #     - /usr/src/app/node_modules
  #   tty: true
  #   ports: 
  #     - "3000:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true

  # frontend:
  #   build: 
  #     context: react
  #   container_name: frontend
  #   working_dir: /usr/src/app
  #   networks: 
  #     - node-network
  #   volumes: 
  #     - /usr/src/app/node_modules    
  #   tty: true
  #   ports: 
  #     - "5173:4173"

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    environment: 
      - POSTGRES_PASSWORD=1234
    ports: 
      - "5432:5432"
    networks: 
      - node-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
networks: 
  node-network:
    driver: bridge
    